In [2]:
import torch

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8106, 0.3353, 0.3850],
        [0.3055, 0.6729, 0.6933],
        [0.9467, 0.8243, 0.2076],
        [0.7691, 0.8926, 0.1514],
        [0.0569, 0.4735, 0.4652]])


In [5]:
#create a tensor (default on cpu)
tensor = torch.tensor([1,2,3], device="cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
#move tensor to GPU if avaialble
device= "cuda" if torch.cuda.is_available() else "cpu"
tensor_gpu = tensor.to(device)
tensor_gpu.device

device(type='cuda', index=0)

In [7]:
!nvidia-smi

Wed May 15 18:41:55 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 552.22                 Driver Version: 552.22         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   49C    P5             25W /  270W |    2666MiB /   8192MiB |     38%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [12]:
torch.cuda.manual_seed(1234)
A = torch.rand(2,3)
A.to("cuda")

tensor([[0.8619, 0.4049, 0.6485],
        [0.9174, 0.9941, 0.3810]], device='cuda:0')

In [11]:
torch.cuda.manual_seed(1234)
B = torch.rand(2,3)
B.to("cuda")

tensor([[0.8704, 0.8673, 0.7483],
        [0.8945, 0.9981, 0.7512]], device='cuda:0')

In [14]:
out = A @ B.T

In [20]:
import numpy as np
max = out.argmax()
max

tensor(3)

In [21]:
min = out.argmin()
min

tensor(0)

In [34]:
new_tensor = torch.rand(1,1,1,10)
new_tensor

tensor([[[[0.5632, 0.5920, 0.0840, 0.2429, 0.4780, 0.8209, 0.8345, 0.6158,
           0.9919, 0.0134]]]])

In [35]:
new_tensor=new_tensor.squeeze(0,1,2)
new_tensor

tensor([0.5632, 0.5920, 0.0840, 0.2429, 0.4780, 0.8209, 0.8345, 0.6158, 0.9919,
        0.0134])

In [36]:
new_tensor.shape

torch.Size([10])